name: check_andbiz

on:
  schedule:
    # JST 7:00-22:00 = UTC 22:00(前日)-13:00
    # 30分ごとに実行（0時-7時は実行しない）
    - cron: '*/30 22-23 * * *'  # UTC 22:00-23:30 (JST 翌7:00-8:30)
    - cron: '*/30 0-13 * * *'   # UTC 0:00-13:30 (JST 9:00-22:30)
  workflow_dispatch:  # 手動トリガーを追加

jobs:
  compare-and-notify:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests chromedriver-autoinstaller

    - name: Run check_andbiz script
      id: compare-sheets
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python check_andbiz.py