name: Simple Suginami Site Test

on:
  workflow_dispatch:

jobs:
  simple-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Setup Chrome and Virtual Display
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable xvfb
        export DISPLAY=:99
        Xvfb :99 -ac -screen 0 1280x1024x24 &

    - name: Run simple test
      timeout-minutes: 15
      env:
        DISPLAY: :99
      run: |
        python simple_test.py