name: Suginami Facility Monitor

on:
  # schedule:
  #   - cron: '*/30 7-23 * * *'  # GitHub Actions環境では技術的制約により実行困難
  workflow_dispatch:

jobs:
  monitor-facilities:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable xvfb

    - name: Setup Chrome and Virtual Display
      run: |
        export DISPLAY=:99
        Xvfb :99 -ac -screen 0 1280x1024x24 &
        sleep 2

    - name: Run Suginami facility monitor
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        DISPLAY: :99
      timeout-minutes: 20
      run: |
        python suginami_seshion_nishiogi.py

    - name: Commit JSON updates if any
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add suginami_availability.json
        git diff --staged --quiet || git commit -m "Update Suginami facility availability data"
        git push || echo "No changes to push"