name: 杉並サイトアクセステスト

on:
  workflow_dispatch:  # 手動実行のみ

jobs:
  test-access:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 playwright
        playwright install chromium
        playwright install-deps

    - name: Run access tests
      run: |
        chmod +x test_suginami_access.py
        python test_suginami_access.py

    - name: Show test results
      if: always()
      run: |
        echo "テスト実行完了"
        echo "詳細はログを確認してください"
